name: iOS Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Xcode
      uses: actions/setup-xcode@v2
      with:
        xcode-version: '12.x' # replace with your desired Xcode version
    - name: Install Carthage
      run: |
        brew install carthage
    - name: Install dependencies
      run: |
        carthage bootstrap --platform iOS
        pod install
    - name: Build app
      run: xcodebuild -project MapboxSpeech.xcodeproj -scheme MapboxSpeechTests -destination 'platform=iOS Simulator,name=iPhone 12' build
